[project]
name = "deletetweets"
version = "0.1.0"
description = "A script to delete tweets from X (formerly Twitter) automatically using Selenium"
readme = "README.md"
authors = [
    { name = "anna-davydova", email = "davydova.anna@outlook.com" }
]
requires-python = ">=3.12"
dependencies = [
    "pip-system-certs>=5.3",
    "selenium>=4.47.0",
    "setuptools>=84.0.0",
    "undetected-chromedriver>=3.5.5",
]

[project.scripts]
deletetweets = "deletetweets:main"
